
import "./globals.css";
import Head from "next/head";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Colr+Emoji+Glyf"
          rel="stylesheet"
        />
        <script src="/socket.io/socket.io.js"></script>
        <script>const socket = io();</script>
      </Head>
      <body>{children}</body>
    </html>
  );
}
